apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::344845126663:role/8e73204021604753-eks-nodegroup-NodeInstanceRole
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2024-01-03T10:45:24Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "3519"
  uid: 22d06f41-4643-4448-8961-da9ce42b4ee6
data:
  mapUsers: |
    - userarn: arn:aws:iam::344845126663:user/ahmed.ali
      username: admin
      groups:
        - system:masters
